### PR TITLE
Add claim ID log for testing. MCP-2429

### PR DESCRIPTION
**Pull request by wlin2019**
Adding additional log for claim ID along automatedClaim process route.

## What was the problem?

Associated tickets or Slack threads:
MCP-2429

## How does this fix it?[^1]
Add log

## How to test this PR
- Step 1
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

### CODE REVIEW

**Review by alan-amida — APPROVED** [review]

**Review by au2 — CHANGES_REQUESTED** [review]
This is not what I expected. I need the claim id (from claimSubmissionId) in AbdRabbitReceiever receiveMessage. ICN has already been available there. I am hoping that it will be populated from MAS calls. This is for svc-lighthouse-api.

**Comment by au2** [comment]
Also I need the  ICN logged in MAS workflow. The best place appears to be MASController automated claim method. ICN is available from VeteranIdentifiers But please be defensive about nulls. @wlin2019

**Comment by au2** [comment]
One last thing we need to remove FileNumber loggin from BIP Claim Evidence API service. It is PII. Please look at uploadEvidenceFile jn BIP CE API service.  Leave some logs but without the file id. @wlin2019

**Comment by wlin2019** [comment]
> This is not what I expected. I need the claim id (from claimSubmissionId) in AbdRabbitReceiever receiveMessage. ICN has already been available there. I am hoping that it will be populated from MAS calls. This is for svc-lighthouse-api.

Add ICN log in AbdRabbitReceiver.

**Comment by wlin2019** [comment]
> Also I need the ICN logged in MAS workflow. The best place appears to be MASController automated claim method. ICN is available from VeteranIdentifiers But please be defensive about nulls. @wlin2019

The ICN logs have been added from MASController to MasPollingProcessor.

**Comment by wlin2019** [comment]
> One last thing we need to remove FileNumber loggin from BIP Claim Evidence API service. It is PII. Please look at uploadEvidenceFile jn BIP CE API service. Leave some logs but without the file id. @wlin2019

Removed. But the file ID still appears in logging the call header. Added a TODO note to remove it after test.

**Review by au2 — APPROVED** [review]

**Pull request merged**
