### PR TITLE
MCP-2147 - Enforce required ClaimCondition fields to be NotNull

### PR DESCRIPTION
**Pull request by alan-amida**
## What was the problem?

- Execute the automatedClaim endpoint without diagnosticCode parameter in the request body. You will see the response code: 200. 
- Note:  If the "disabilityActionType" and  "disabilityClassificationCode" is not in the request body also giving the response code: 200 instead of 400
  - UPDATE: Kalai says this is expected behavior, so  nothing will be done to those here
- Expected response code : 400 

Associated tickets or Slack threads:

- [MCP-2147](https://amida.atlassian.net/browse/MCP-2147)

## How does this fix it?[^1]

- We now enforce, for `MasAutomatedClaimPayload`'s child Object `ClaimCondition` that the following fields be enforced as REQUIRED via `@NotNull`
  - `diagnosticCode`
  - ~~`disabilityActionType`~~
  - ~~`disabilityClassificationCode`~~

## How to test this PR
- Step 1: Submit a POST request to `/v2/automatedClaim` with a payload that omits `claimDetail.conditions.diagnosticCode` ~~and/or `claimDetail.conditions.disabilityActionType` and/or `claimDetail.conditions.disabilityClassificationCode`in any combination~~
  - Verify you receive a `400 Bad Request` with a message indicating the field(s) cannot be null
- Step 2: Submit a valid POST request to `/v2/automatedClaim` with a valid payload
  - Verify you receive a `200 OK`

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.

### CODE REVIEW

**Review by wlin2019 — APPROVED** [review]
LGTM

**Comment by dimitri-amida** [comment]
@alan-amida, @rajesh-Krishnasamy  I don't see disabilityClassificationCode used anywhere in our code. If it is required, is it supposed to be used somewhere?

**Comment by alan-amida** [comment]
@Kalai4amida has said that they are not required, so I might have to roll back the changes on those two optional fields.

I will discuss with her on expected behavior.

**Comment by alan-amida** [comment]
OK, as per Kalai:
> Alan,  disabilityActionType and disabilityClassificationCode these fields are not required and I think it is working fine. Honestly, we didn't have  defined expected result for this.

So I will be undoing those changes for those 2 optional fields, but keeping what I did for the `diagnosticCode`

Please stand by

**Comment by alan-amida** [comment]
end2endTest was run and passes

@dimitri-amida this is ready for re-review

**Review by dimitri-amida — APPROVED** [review]
lgtm

**Pull request merged**
