### PR TITLE
 Add actuator readiness URL for svc-bip-api 

### PR DESCRIPTION
**Pull request by Ponnia-M**
## What was the problem?
Add actuator health check to use the latest readiness urls

Associated tickets or Slack threads:
- #2398 

## How does this fix it?[^1]
Creates an endpoint for readiness for svc-bip-api

## How to test this PR
- Run integration test

### CODE REVIEW

**Comment by msnwatson** [comment]
I'm almost wanting to hold off on implementing this for this service given the complexities still ongoing in getting the service functional. That's my bad for not calling that out earlier.  If it seems to be working, then we can move forward but if you run into any issues, I'd say we keep the PR open until the service gets into a good state. cc'ing the folks most involved @tejans24  @chengjie8  @nelsestu  @agile-josiah

**Review by msnwatson — COMMENTED** [review]
see above, feel free to re-request if necessary

**Review by agile-josiah — APPROVED** [review]
LGTM

**Review by msnwatson — APPROVED** [review]
discussed in standup and confirmed with folks working on the BIP effort

**Pull request merged**
