### PR TITLE
Introduces a metric_logger ruby implementation for use in the bgs sevice

### PR DESCRIPTION
**Pull request by nelsestu**
Adds a request count metric for requests started, and requests completed, and a request latency metric for calls out to the BGS service.

## What was the problem?
We had extremely limited visibility into the goings on with the external calls that the VRO svc-bgs-api client service makes. 

Associated tickets or Slack threads:
- #2980

## How does this fix it?[^1]
With this PR, we'll be able to see request start, complete counts as well as tracking the request latency.

## How to test this PR
- Running the bgs integration test will now submit metrics via the datadog api.

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

### CODE REVIEW

**Comment by ponny-m** [comment]
@lisac Have these changes been tested locally and they were successful?

**Comment by lisac** [comment]
> @lisac Have these changes been tested locally and they were successful?

Yes, these were tested locally with unit tests. Unit tests were successful.

**Review by ponny-m — APPROVED** [review]
LGTM

**Comment by lisac** [comment]
reviewers: please hold. i managed to introduce buggy behavior, i suspect tracing back to reconciling merges around ruby gems. thank you to Ponnia for flagging.

**Comment by lisac** [comment]
@Ponnia-M : thank you for flagging the issue with the spike in failed GH checks. I think it's resolved - would you please re-review? 

It turns out the Gemfile.lock got out of sync when I merged in other changes, and that led to failures starting up docker containers. With my latest update ([eb00f4a](https://github.com/department-of-veterans-affairs/abd-vro/pull/3075/commits/eb00f4aa8cffd5ab180379d7f879688aa8fad6f8)), I see the GH checks are now passing, with the exception of one; however, that one is a known failure that's also present in the default branch.

**Pull request merged**
