### PR TITLE
MCP-1870 Python Lint + Code Format

### PR DESCRIPTION
**Pull request by anthonyvelazquez**
# MCP-1870 Python Lint + Code Format 

## Description

Added linting, code formatting and a check to Github

### Jira Tickets

- [MCP-1870](https://amida.atlassian.net/browse/MCP-1870)

### CODE REVIEW

**Review by jbregstone — COMMENTED** [review]
If the format and lint command is run in in Github actions, will the code changes be reflected in the PR? If not, we could add the command to a pre-push config.

**Review by au2 — CHANGES_REQUESTED** [review]
Can we add this to ./gradle build as well ?

**Comment by au2** [comment]
@anthonyvelazquez consider https://github.com/linkedin/pygradle. did not dig in much but fro what i understand it does have some of the task that are very useful. flake8 for example. it does appear that it will require some setup.

**Review by ianwolson — APPROVED** [review]

**Comment by au2** [comment]
I think I will move these changes as add a new ticket for gradle integration

**Review by au2 — APPROVED** [review]

**Pull request merged**
