### PR TITLE
Dockerfile-python: add longer timeout for pip install to repair CI workflow

### PR DESCRIPTION
**Pull request by greene858**
## What was the problem?
CI workflow was failing when building python image for cc

Associated tickets or Slack threads:
[Heads up: The CI workflow started failing this morning.](https://dsva.slack.com/archives/C04QLHM9LR0/p1689609256328389)

## How does this fix it?
Well, it upgrades pip, like the error message said to

### CODE REVIEW

**Comment by yoomlam** [comment]
Are you sure that works? I tried that locally and it still failed.

**Comment by greene858** [comment]
> Are you sure that works? I tried that locally and it still failed.

It did work on my docker command, can you please give me details on the fail you are seeing, thx

**Comment by yoomlam** [comment]
> > Are you sure that works? I tried that locally and it still failed.
> 
> It did work on my docker command, can you please give me details on the fail you are seeing, thx

It continued to fail with the same error as I posted in the Slack thread.

Here's the CI run on this PR's branch: [3. Continuous Integration (run tests and checks)](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5588104495). It (eventually) passed, so I must have done something wrong or pip repos were updated.

I re-ran a previously failed run and it got passed the error: https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5581584922/jobs/10215025287
so I'm thinking this PR is not needed.

[Recent runs](https://github.com/department-of-veterans-affairs/abd-vro/actions/workflows/continuous-integration.yml) are not showing the original error any more.

**Comment by yoomlam** [comment]
The [error popped up](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5589686487/jobs/10218339806#step:4:477) again, but re-running made it pass.

**Comment by greene858** [comment]
upgrade pip did not stop the build fails. Failures were intermittent, sometimes domain-cc failed, sometimes svc-hoppy-usage failed; but the code didn’t change between success and fail - something outside of the code must be involved. My research suggests that intermittent PIP fails can be mitigated with the timeout setting. 

So, I removed the upgrade pip parameter and added default-timeout=100

**Review by yoomlam — APPROVED** [review]
Thanks for digging into it!

**Pull request merged**
