### PR TITLE
Gradle: plugin cleanup

### PR DESCRIPTION
**Pull request by yoomlam**
## What was the problem?

Projects were referring to Gradle plugins unnecessarily.

## How does this fix it?

- remove unnecessary plugin references
- use local.std.java.library-conventions plugin
- rm local.std.java.library-spring-conventions
- move spotless plugin to shared
- move src/docker/Dockerfile to project folder

### CODE REVIEW

**Comment by yoomlam** [comment]
[3. Continuous Integration (run tests and checks)](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5416089262)

**Comment by yoomlam** [comment]
TODO: ensure this PR doesn't introduce SecRel alerts. In order to check that, SecRel needs to be passing first ([asked Tom](https://dsva.slack.com/archives/C04CA47HV96/p1688068812025819)).

**Comment by yoomlam** [comment]
[3. Continuous Integration (run tests and checks)](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5416314576)

**Review by msnwatson — APPROVED** [review]

**Comment by yoomlam** [comment]
[SecRel dev_ (yoom/gradle-plugin-cleanup)](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/5419029856)

**Pull request merged**
