### PR TITLE
Clean up build.gradle files with dependency constraints

### PR DESCRIPTION
**Pull request by yoomlam**
# Feature Name 

### What was the problem?

To fix security vulnerabilities, **direct** dependencies were added to update versions of vulnerable **transitive** dependencies. Gradle dependency `constraints` should be used instead so that Gradle subprojects are not unnecessarily directly dependent on them - https://docs.gradle.org/current/userguide/dependency_constraints.html.

### How does this fix it?

Clean up build.gradle files with dependency `constraints`.
Also re-order for consistency, and comment out unused dependencies.

Used task `generateGradleLintReport` to show unused dependencies:
```
./gradlew generateGradleLintReport

cat */build/reports/gradleLint/*.txt
```

For future PR: If desired, using [rich version constraints](https://docs.gradle.org/current/userguide/rich_versions.html) may be better.

## How to test this PR

Run SecRel with each change to make sure they don't cause SecRel alerts.

https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline

### CODE REVIEW

**Comment by yoomlam** [comment]
SecRel run: https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/3201597531

**Comment by yoomlam** [comment]
SecRel passed: https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/3201736799

**Comment by yoomlam** [comment]
SecRel pass: https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/3201869917

**Comment by yoomlam** [comment]
SecRel passed: https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/3202026438

**Review by au2 — APPROVED** [review]

**Comment by au2** [comment]
We will address the warnings in another pr.

**Review by wlin2019 — APPROVED** [review]
LGTM

**Pull request merged**
