### PR TITLE
Rename service-data-access to svc-lighthouse-api folder

### PR DESCRIPTION
**Pull request by yoomlam**
## What was the problem?

`service-data-access` folder name is too general.

## How does this fix it?[^1]

Rename it to `svc-lighthouse-api`. The only changes are:
- settings.gradle
- build.gradle
- renaming the directory

This is only renaming the folder for now -- we'll rename the Docker image in a separate PR.

## How to test this PR
All images are still created

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

### CODE REVIEW

**Comment by wlin2019** [comment]
We may need to add MAS API call service to this one after we review MAS API connection information. MAS API and Lighthouse API accesses may be able share some codes/resources. At present, we implement MAS API service in service:provider. But as we may need to access Lighthouse API along with processing MAS API query, the current attempt to host the MAS API service in service:provider may need to be changed. Therefore, can we hold on this at present?

**Comment by yoomlam** [comment]
> We may need to add MAS API call service to this one after we review MAS API connection information. MAS API and Lighthouse API accesses may be able share some codes/resources. At present, we implement MAS API service in service:provider. But as we may need to access Lighthouse API along with processing MAS API query, the current attempt to host the MAS API service in service:provider may need to be changed. Therefore, can we hold on this at present?

API calls to MAS vs Lighthouse should be in different microservices and hence different directories and different Docker containers. If they share code, create a separate library project that they both can depend on.

**Comment by wlin2019** [comment]
> 

That may need additional inter-container "calls". But at present we have some assumptions on the MAS API connection and the data. When we get the MAS access. we should have a better picture.

**Comment by yoomlam** [comment]
> At present, we implement MAS API service in service:provider.

It should not be implement there -- that directory is to implement services that support VRO's API -- see https://github.com/department-of-veterans-affairs/abd-vro/wiki/Code-structure#gradle-subproject-dependencies.

A new `svc-mas-api` folder should be created for a microservice that connects to the MAS API.

**Comment by yoomlam** [comment]
Maybe I'm not understanding your approach. Let's have a call if the following doesn't make sense.

> That may need additional inter-container "calls". 

Common code can be put in a `lib-api-helper` (or whatever name makes sense) Gradle subproject. Then `svc-lighthouse-api` and `svc-mas-api` would have a `implementation project(':lib-api-helper')` in their `build.gradle`.
No "inter-container calls" are needed -- the new library would be treated like any other dependency. 

> But at present we have some assumptions on the MAS API connection and the data. When we get the MAS access. we should have a better picture.

We have MAS's API spec here: https://gist.github.com/rajesh-Krishnasamy/ed169256ff17f51dc07cb671f450c5ce

**Comment by yoomlam** [comment]
@wlin2019 Are you good with merging PR now?

**Comment by yoomlam** [comment]
@wlin2019 Is there any issue or concern preventing this PR from being merged?

**Review by wlin2019 — APPROVED** [review]
I haven't tested it. But it works, I'm okay to merge it.

**Pull request merged**
