### PR TITLE
Remove dependence on VA starter Gradle plugins: phase 2

### PR DESCRIPTION
**Pull request by yoomlam**
Follow-on to #1549

## What was the problem?

Address remaining problems from #1549 and declutter plugins for easier management

- #1514

## How to test this PR

PR checks pass and end2end tests pass

1. Remove Gradle cache of va.starter plugins:
```
cd ~/.gradle/caches/modules-2/files-2.1 # may be different path for your system
rm -rf starter.* gov.va.starter
```
2. `unset GITHUB_ACCESS_TOKEN` and build locally

### CODE REVIEW

**Comment by yoomlam** [comment]
[PR: End-to-end test for v2](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/4944797226)

**Comment by yoomlam** [comment]
[2. (Internal) SecRel workflow](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/4950041932)

**Comment by yoomlam** [comment]
[2. (Internal) SecRel workflow](https://github.com/department-of-veterans-affairs/abd-vro-internal/actions/runs/4950579490)

**Comment by yoomlam** [comment]
[PR: End-to-end test for v2](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/4951042202)

**Review by tcraghu — APPROVED** [review]

**Review by msnwatson — APPROVED** [review]

**Comment by yoomlam** [comment]
image

**Pull request merged**
