### PR TITLE
Upgrade rack version warnings for bgs-api

### PR DESCRIPTION
**Pull request by ponny-m**
Fixing Synk warnings ([High and medium severity](https://github.com/department-of-veterans-affairs/abd-vro-internal/security/code-scanning?query=tool%3A%22Snyk+Open+Source%22+ref%3Arefs/heads/develop+is%3Aopen)) regarding a Denial of Service (DoS) vulnerability in rack in our bgs-api gemfile. 

**Suggested Remediation**: Upgrade rack to version 2.2.8.1, 3.0.9.1 or higher.

### CODE REVIEW

**Review by msnwatson — CHANGES_REQUESTED** [review]
you'll need to run the correct bundler commands to change the Gemfile.lock file as well and add that to your commit

**Comment by ponny-m** [comment]
@msnwatson It should be all good to go now. Thanks.

**Review by ponny-m — COMMENTED** [review]
Fixed these

**Review by ponny-m — COMMENTED** [review]
Done

**Comment by nelsestu** [comment]
@Ponnia-M I am happy for your version upgrade version to go in as the solution for this.  On Friday, I started to document an issue in the sprint to track this open vulnerability.  Today I finished writing the details and assigned it to you.  So please continue with this PR as the solution and thanks for your work on this.  

https://app.zenhub.com/workspaces/vro-team-6557e67173391c000e1409f3/issues/gh/department-of-veterans-affairs/abd-vro/2694

**Review by nelsestu — APPROVED** [review]
Once Mason's comments are addressed, this looks good to go.

**Review by msnwatson — APPROVED** [review]

**Pull request merged**
