### PR TITLE
Bump Dockerfile to flyway/flyway:9.4.0-alpine

### PR DESCRIPTION
**Pull request by yoomlam**
# Feature Name 

### What was the problem?

`flyway`'s dependency on `jackson` java libraries with vulnerabilities is causing [SecRel to fail](https://lighthouseva.slack.com/archives/C02PTSZKM8W/p1665076946279279?thread_ts=1665074050.686019&cid=C02PTSZKM8W) on develop

### How does this fix it?

Bump Dockerfile to `flyway/flyway:9.4.0-alpine`

## How to test this PR

https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline

### CODE REVIEW

**Comment by yoomlam** [comment]
Added to [existing flyway issue](https://github.com/flyway/flyway-docker/issues/109#issuecomment-1270507087)

**Review by au2 — CHANGES_REQUESTED** [review]
Looks like flyway/flyway:9.4.0-alpine is not available in docker hub yet. Waiting.

**Comment by yoomlam** [comment]
```
manifest for flyway/flyway:9.4.0-alpine not found: manifest unknown: manifest unknown
> Task :db-init:docker FAILED
```
[Related Slack thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1665601200682349)

**Review by wlin2019 — DISMISSED** [review]

**Review by wlin2019 — COMMENTED** [review]
Got error:
failed to create LLB definition: docker.io/flyway/flyway:9.4.0-alpine: not found

**Comment by jmcruz1983** [comment]
Any ETA for `9.4.0-alpine` production release?

**Comment by yoomlam** [comment]
> Any ETA for `9.4.0-alpine` production release?

@jmcruz1983 I think you're meaning to post to https://github.com/flyway/flyway-docker/issues/109

**Comment by yoomlam** [comment]
This will likely fix recent SecRel failures.

**Review by au2 — APPROVED** [review]

**Comment by sethdarragile6** [comment]
Local testing seemed fine, but it still seems to be failing SecRel. I'll regroup with Yoom tomorrow on this. Thanks

**Comment by sethdarragile6** [comment]
With flyway bumped to 9.5, all tests and scans look! Can I get one more approval so I can merge this? Thanks for your patience, all.

**Review by dimitri-amida — APPROVED** [review]
lgtm

**Pull request merged**
