### PR TITLE
Merging develop into main

### PR DESCRIPTION
**Pull request by alan-amida**
Merging `develop` into `main`

### CODE REVIEW

**Comment by yoomlam** [comment]
> Or are we force-pushing to `main`?

I think we should update main to point to the latest `develop` commit.

**Review by au2 — APPROVED** [review]

**Comment by au2** [comment]
@alan-amida please do not squash while merging. It causes problems next time we want to merge.

**Comment by alan-amida** [comment]
OK. This is something I cannot force merge, so I'll need another approval.

**Review by yoomlam — APPROVED** [review]

**Review by yoomlam — APPROVED** [review]

**Comment by alan-amida** [comment]
@au2 approve again, please?

**Comment by alan-amida** [comment]
This is what I see:
image

We can enable these, but which strategy works best for y'all?
image

**Comment by yoomlam** [comment]
Don't squash -- https://github.com/department-of-veterans-affairs/abd-vro/pull/1483#issuecomment-1515336279

I recommend doing https://github.com/department-of-veterans-affairs/abd-vro/pull/1483#issuecomment-1515111592 locally (to retain each PR commit) and pushing `main` to GH.

**Comment by alan-amida** [comment]
> I recommend doing https://github.com/department-of-veterans-affairs/abd-vro/pull/1483#issuecomment-1515111592 locally (to retain each PR commit) and pushing your local main to GH.

So in this case, pull and update my local `main`, then pull from remote `develop` (into `main`) which will effectively perform a local auto-merge (defaulting to fast-forward strategy), and then push that up?
```Console
git branch main
git pull origin main
git pull origin develop
```
Hopefully it auto-merges cleanly. If not, we're in a merge state — resolve any conflicts.
```Console
git push origin main
```

?

**Comment by yoomlam** [comment]
I was thinking more like:
```
# Checkout branch           
  git checkout "main"     
# Hard Reset main to point to the latest develop
  git reset --hard develop
```
The result is `main` and `develop` will point to the exact same commit hash.

**Pull request merged**
