### PR TITLE
MCP-1969 End2end test in workflow

### PR DESCRIPTION
**Pull request by au2**
## What was the problem?

There was not an automated test simulating end to end test QA team does.

There was no automated end to end test.

Associated tickets or Slack threads:

- [MCP-1969](https://amida.atlassian.net/browse/MCP-1969)

## How does this fix it?[^1]

A new end to end test is added as a github workflow and run for each pr. The test is run as a gradle task after the docker-compose is run.

## How to test this PR
- You can manually test if the end to end test is running.

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

### CODE REVIEW

**Comment by wlin2019** [comment]
It looks fine to me. But when I tried to test it, I saw the failure.

./gradlew end2endTest

Two test failed:
VroV1Tests. positive6602Case01()
VroV1Tests. positive7101Case01()

**Review by wlin2019 — APPROVED** [review]
I built and test (./gradlew end2endTest) again. This time is successful.

**Comment by anthonyvelazquez** [comment]
@wlin2019 Did you do anything else outside of the building and testing an additional time? I ran into the same errors but I've built and reran the test multiple times and no change on my end.

Specifially, my error for both is:
```
java.lang.IllegalStateException: Timeout on blocking read for 15000000000 NANOSECONDS
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:123)
	at reactor.core.publisher.Mono.block(Mono.java:1731)
	at org.springframework.test.web.reactive.server.DefaultWebTestClient$DefaultRequestBodyUriSpec.exchange(DefaultWebTestClient.java:361)
	at gov.va.vro.end2end.util.RestHelper.getAssessment(RestHelper.java:46)

**Comment by au2** [comment]
@anthonyvelazquez I added an environment variable VRO_E2E_RESPONSE_TIMEOUT and increased the timeout to 20 seconds. It looks like the rest call to vro is timing out (health assessment probably). It could be that your machine relatively runs slow in which case you can increase the time out. But also please make sure all the services in docker-compose are running and have error free logs.

**Review by anthonyvelazquez — APPROVED** [review]

**Pull request merged**
