### PR TITLE
Domain EE: 1821: Fix issue with possible log injection

### PR DESCRIPTION
**Pull request by dfitchett**
## What was the problem?

Previous impl results in possible [log injection](https://github.com/department-of-veterans-affairs/abd-vro/security/code-scanning/1307)
Associated tickets or Slack threads:
- https://dsva.slack.com/archives/C01Q7979Z7D/p1692132032729879

## How does this fix it?[^1]

Forces json input to contain an array of integers. Before this change, it would coerce strings to ints.

See successful [codeQL](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5872063590/job/15922879945) run

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

### CODE REVIEW

**Comment by yoomlam** [comment]
It's not clear that this PR address the error: https://github.com/department-of-veterans-affairs/abd-vro/security/code-scanning/1307. I think the page would state "Fixed by ...".
Also the error refers to `domain-ee/ee-max-cfi-app/src/python_src/api.py:60` as the problem.

**Comment by dfitchett** [comment]
> It's not clear that this PR addresses the error: [Log Injection](/department-of-veterans-affairs/abd-vro/security/code-scanning/1307). I think the page would state "Fixed by ...". Also the error refers to `domain-ee/ee-max-cfi-app/src/python_src/api.py:60` as the problem, originating from [domain-ee/ee-max-cfi-app/src/python_src/api.py:44](https://github.com/department-of-veterans-affairs/abd-vro/blob/d28431f8a565220cd4ecb073f653e5f5275a34ca/domain-ee/ee-max-cfi-app/src/python_src/api.py#L44-L44).

As outlined in this slack [thread](https://dsva.slack.com/archives/C01Q7979Z7D/p1692132032729879), I changed the log statement to return just the ratings from response and created method that sanitizes input before logging as detailed in the recommended fix in the original [vulnerability](https://github.com/department-of-veterans-affairs/abd-vro/security/code-scanning/1307).

**Comment by yoomlam** [comment]
Ran [PR: CodeQL security scan](https://github.com/department-of-veterans-affairs/abd-vro/actions/runs/5881989064) to see if [the alert](https://github.com/department-of-veterans-affairs/abd-vro/security/code-scanning/1307) is updated with "Fixed by ..." note.

**Review by yoomlam — APPROVED** [review]
Thanks!

**Review by nanotone — APPROVED** [review]
LGTM

**Pull request merged**
