### PR TITLE
MCP-1820 - Remove all Lighthouse API related credential from repo and set them to environment variables

### PR DESCRIPTION
**Pull request by wlin2019**
…. See MCP-1820.

Move all Lighthouse API access related credential to environment variables

## Description

Remove all lighthouse API access related credentials from the repo, and set them to environment variables.

To setup the environment variables to build the application, run the environment setup utility in [abd-vro-dev-secrets](https://github.com/department-of-veterans-affairs/abd-vro-dev-secrets) repo. See README there for the details.

### What was the problem?

For security concern, we should not leave credentials in the repo as it is set as PUBLIC.

### How does this fix it?

Remove all the lighthouse API access credentials in the property files, and use environment variables.

### Jira Tickets

MCP-1820

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How to test this PR

- Step 1. Set up local environment variables as specified in README in abd-vro-dev-secrets repo.
- Step 2. Follow the README in this repo to build the application.

## Reminders

- Review [Pull-Requests](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests) guidelines
- [ ] If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) and
[Roadmap](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Roadmap) wiki pages
- [ ] If changing software behavior, post a link to the PR in Slack channel #benefits-virtual-regional-office

### CODE REVIEW

**Comment by au2** [comment]
@wlin2019 can you merge develop to this branch please?

**Review by au2 — CHANGES_REQUESTED** [review]
@wlin2019 you need to put content of the file pem to an environment variable. We do not want to specify a file in Kubernetes.

@advcoder please correct me if I am wrong.

**Comment by wlin2019** [comment]
> @wlin2019 you need to content of the file pem to an environment variable. We do not want to specify a file in Kubernetes.
> 
> @advcoder please correct me if I am wrong.

The setenv.sh will do that. There is no pem file in this project.

**Review by au2 — APPROVED** [review]
I removed pem files and the end point works after setting the environment variables.

**Review by advcoder — APPROVED** [review]

**Review by au2 — CHANGES_REQUESTED** [review]
Shouldn't the env vars on app/src/docker/docker-compose.yml and service-data-access/src/integrationTest/resources/application-test.properties be consistent?

**Review by au2 — APPROVED** [review]

**Pull request merged**
