### PR TITLE
MCP 2444: Remove duplicate data model

### PR DESCRIPTION
**Pull request by jbregstone**
## What was the problem?

Duplicate code presents maintainability issues. We need to copy over shared files in Dockerfile, according to Ryan.

Associated tickets or Slack threads:

- [MCP-2444](https://amida.atlassian.net/browse/MCP-2444)

## How does this fix it?[^1]

Add a line to copy over shared files to each python docker image.

## How to test this PR
- Step 1 Run end2end tests
- Step 2[^secrel]

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

### CODE REVIEW

**Comment by yoomlam** [comment]
I'm delegating the review of this PR to @nanotone and @greene858.
As long as it works, I'm good with the changes.

**Comment by jbregstone** [comment]
I can not recreate the githb actions build failure locally. It says `COPY failed: no source files were specified`. @anthonyvelazquez any ideas?

**Comment by anthonyvelazquez** [comment]
Taking a look. Only thing I can see might be an issue is if the items its trying to copy aren't available on Github but I'll download locally and see

**Review by anthonyvelazquez — APPROVED** [review]
Looks like its all 🟢 . Not sure if you figured it out but from what I found, when running a `COPY` with more than 1 file, the destination must end in a `/` other than that, it might have been a bad path so it couldn't find the items to copy

**Comment by jbregstone** [comment]
> Looks like its all 🟢 . Not sure if you figured it out but from what I found, when running a `COPY` with more than 1 file, the destination must end in a `/` other than that, it might have been a bad path so it couldn't find the items to copy

Still failing end2end it seems

**Review by greene858 — COMMENTED** [review]
Moving validation from util to data_model makes sense, however nothing in the comments or the README explain how it should be used. Also need clarification why some claim types use data_model and some use their own utils.py (e.g. cancer, 6510). Please standardize on data_model, if there is a specific document type that is being validated, please reference that in the comments of each Validator

**Comment by jbregstone** [comment]
> Moving validation from util to data_model makes sense, however nothing in the comments or the README explain how it should be used. Also need clarification why some claim types use data_model and some use their own utils.py (e.g. cancer, 6510). Please standardize on data_model, if there is a specific document type that is being validated, please reference that in the comments of each Validator

Thank you for the feedback, I pushed changes to have all the conditions processors use the `data_model.py` for validation. I added a section to the readme and referenced the document type.

**Review by greene858 — APPROVED** [review]
LGTM

**Pull request merged**
