### PR TITLE
Move svc-lighthouse-api to its own repo

### PR DESCRIPTION
**Pull request by msnwatson**
## What was the problem?

The titular service has not been used for over a year, cluttering the repo, our SecRel pipelines, and LHDI environments.

Associated tickets or Slack threads:
- #2697 

## How does this fix it?[^1]

* Moves the service into its own repo at https://github.com/department-of-veterans-affairs/abd-vro-svc-lighthouse-api

## How to test this PR
- Remove deployments in escalating environments

[^1]: [Pull-Requests guidelines](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests). If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) wiki page.
[^secrel]: To check if a PR will succeed in the SecRel workflow, [test PRs in the SecRel pipeline](https://github.com/department-of-veterans-affairs/abd-vro-internal/wiki/Secure-Release-process#to-test-prs-in-the-secrel-pipeline).

### CODE REVIEW

**Review by chengjie8 — APPROVED** [review]
LGTM

**Comment by lisac** [comment]
looks good to me. two questions, neither of which should hold up the PR.

1. the helm chart `deploy.sh` handles a case for `svc-lighthouse-api` - is that still needed?   https://github.com/department-of-veterans-affairs/abd-vro/blob/b3cd3a17604666d751479647e5659f2dd330f36d/helm/deploy.sh#L83-L84

2. should we re-generate `image_vars.src` to remove its references to`svc-lighthouse-api`?  for example: https://github.com/department-of-veterans-affairs/abd-vro/blob/b3cd3a17604666d751479647e5659f2dd330f36d/scripts/image_vars.src#L8

if these are relevant, could be addressed in a follow-up PR.

**Review by lisac — APPROVED** [review]

**Review by nelsestu — APPROVED** [review]
Just what I'd expect to see. 6k removed 1 added

**Comment by msnwatson** [comment]
> looks good to me. two questions, neither of which should hold up the PR.
> 
> 1. the helm chart `deploy.sh` handles a case for `svc-lighthouse-api` - is that still needed?   https://github.com/department-of-veterans-affairs/abd-vro/blob/b3cd3a17604666d751479647e5659f2dd330f36d/helm/deploy.sh#L83-L84
> 2. should we re-generate `image_vars.src` to remove its references to`svc-lighthouse-api`?  for example: https://github.com/department-of-veterans-affairs/abd-vro/blob/b3cd3a17604666d751479647e5659f2dd330f36d/scripts/image_vars.src#L8
> 
> if these are relevant, could be addressed in a follow-up PR.

Good catches, @lisac. Nothing would go wrong if we waited on these, but I'll go ahead and knock them out

**Pull request merged**
