### PR TITLE
Add mock service based on BGS wsdl

### PR DESCRIPTION
**Pull request by greene858**
This is a mock of the BGS API based on the BGS wsdl using [imposter](https://github.com/outofcoffee/imposter)
This is a draft - the mock does not return valid responses yet

- #1354

### CODE REVIEW

**Comment by nanotone** [comment]
Reposting this from Slack:

The Ruby SOAP ecosystem (Savon & friends, in this case Wasabi the WSDL parser) uses [http GET to fetch remote WSDLs](https://github.com/savonrb/wasabi/blob/master/lib/wasabi/resolver.rb#L43-L49). However, when I hit my local mock BGS it rejects GET requests:

```
$ curl -v http://mock-bgs-api:8080/DevelopmentNotesService/DevelopmentNotesService?WSDL
*   Trying 172.18.0.3:8080...
* Connected to mock-bgs-api (172.18.0.3) port 8080 (#0)
> GET /DevelopmentNotesService/DevelopmentNotesService?WSDL HTTP/1.1
> Host: mock-bgs-api:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 Method Not Allowed
< allow: POST
< content-length: 0
<
```

**Comment by yoomlam** [comment]
Please resolve conflicts.

**Review by tejans24 — APPROVED** [review]
LGTM

**Review by dfitchett — COMMENTED** [review]
Looks good. Just waiting to approve it after the conflicts are resolved and I can run it locally!

**Comment by greene858** [comment]
This pr has been replaced with #1810

**Pull request closed without merging**
