### PR TITLE
MCP-1948: Sinusitis processor

### PR DESCRIPTION
**Pull request by jbregstone**
# Sinusitis processor 

### What was the problem?
No support for sinusitis condition (`6510`).
CFR https://www.law.cornell.edu/cfr/text/38/4.97

### How does this fix it?
Adds python service for sinusitis condition logic. Includes Medication, Procedure and Condition filtering and SME validated codesets. 

Calculated evidence summary fields:
`constantSinusitis` is true only when a Sinusitis diagnosis 'onsetDate' is more than 12 weeks prior to the date of claim.
`radicalSurgery` is true only when a procedure matches the CPT procedures identified as radical surgery. 
`multipleSurgery` is true only when more than two relevant surgeries have been identified. 

The calculated evidence summary is intended to make clear the eligibility of a claim for the fast track. The summary will further the ability of the VRO user to identify claims with sufficient evidence for (most likely a positive) rating. If any of the calculated evidence summary fields are true than the claim should be routed on the fast track. 

There are testing limitations for the procedures algorithm because the sandbox does not supply codes for procedurs and text matching is not optimal for the CPT code system. 

### Jira Tickets

- [MCP-000](https://amida.atlassian.net/browse/MCP-000)

## How to test this PR

    Step 1
    ./gradlew -PenablePrototype=true build check docker:
    -export COMPOSE_PROFILES=prototype

    ./gradlew :app:dockerComposeDown :app:dcPrune :app:dockerComposeUp

- go to Swagger page

- enter "6510" for diagnosticCode

ICN with partial evidence: 1000003, 1000005, 10000271, 17000151, 173, 25

ICN that qualifies for constant sinusitis: 195

## Reminders

- Review [Pull-Requests](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Pull-Requests) guidelines
- [ ] If PR is significant, update [Current Software State](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Current-Software-State) and
[Roadmap](https://github.com/department-of-veterans-affairs/abd-vro/wiki/Roadmap) wiki pages
- [ ] If changing software behavior, post a link to the PR in Slack channel #benefits-virtual-regional-office

### CODE REVIEW

**Comment by anthonyvelazquez** [comment]
@au2 Do we need a PDF template for this new code?

**Review by anthonyvelazquez — APPROVED** [review]
LGTM. Fixed my Lighthouse issue and got a successful response

```
vro-app-1                  | 2022-10-26 02:34:15.538  INFO 1 --- [nio-8080-exec-3] gov.va.vro.controller.DevController      : Getting health assessment for claim 1234 and veteran icn 9000682
vro-app-1                  | 2022-10-26 02:34:15.650  INFO 1 --- [nio-8080-exec-3] g.v.v.s.p.camel.SlipClaimSubmitRouter    : Routing to rabbitmq:claim-submit-exchange?queue=claim-submit&routingKey=code.6510&requestTimeout=60000.
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:15.659  INFO 1 --- [ntContainer#0-1] g.v.v.a.service.AbdRabbitReceiver        : Claim submission for icn=9000682
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:15.708  INFO 1 --- [ntContainer#0-1] g.v.v.a.service.LighthouseApiService     : get httpEntity for token. tokenurl=https://sandbox-api.va.gov/oauth2/health/system/v1/token
vro-svc-lighthouse-api-1   | , scope=launch patient/MedicationRequest.read
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:16.871  INFO 1 --- [ntContainer#0-1] g.v.v.abddataaccess.service.FhirClient   : Get FHIR data from MedicationRequest?patient=9000682&page=1&count=30
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:17.469  INFO 1 --- [ntContainer#0-1] g.v.v.a.service.LighthouseApiService     : get httpEntity for token. tokenurl=https://sandbox-api.va.gov/oauth2/health/system/v1/token
vro-svc-lighthouse-api-1   | , scope=launch patient/MedicationRequest.read
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:18.379  INFO 1 --- [ntContainer#0-1] g.v.v.abddataaccess.service.FhirClient   : Get FHIR data from MedicationRequest?patient=9000682&page=2&count=30
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:19.376  INFO 1 --- [ntContainer#0-1] g.v.v.abddataaccess.service.FhirClient   : Retrieved 14 entries for MEDICATION
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:19.382  INFO 1 --- [ntContainer#0-1] g.v.v.a.service.LighthouseApiService     : get httpEntity for token. tokenurl=https://sandbox-api.va.gov/oauth2/health/system/v1/token
vro-svc-lighthouse-api-1   | , scope=launch patient/Procedure.read
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:20.224  INFO 1 --- [ntContainer#0-1] g.v.v.abddataaccess.service.FhirClient   : Get FHIR data from Procedure?patient=9000682&page=1&count=30
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:20.846  INFO 1 --- [ntContainer#0-1] g.v.v.abddataaccess.service.FhirClient   : Retrieved 19 entries for PROCEDURE
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:20.853  INFO 1 --- [ntContainer#0-1] g.v.v.a.service.LighthouseApiService     : get httpEntity for token. tokenurl=https://sandbox-api.va.gov/oauth2/health/system/v1/token
vro-svc-lighthouse-api-1   | , scope=launch patient/Condition.read
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:21.772  INFO 1 --- [ntContainer#0-1] g.v.v.abddataaccess.service.FhirClient   : Get FHIR data from Condition?patient=9000682&page=1&count=30
vro-svc-lighthouse-api-1   | 2022-10-26 02:34:22.137  INFO 1 --- [ntContainer#0-1] g.v.v.abddataaccess.service.FhirClient   : Retrieved 14 entries for CONDITION
vro-app-1                  | 2022-10-26 02:34:22.148  INFO 1 --- [nio-8080-exec-3] gov.va.vro.controller.DevController      : Returning health assessment for: 9000682

**Review by au2 — CHANGES_REQUESTED** [review]
@jbregstone  Please resolve conflicts and if they are not in yet do the changes in asthma v2.

**Review by anthonyvelazquez — APPROVED** [review]
Giving another 👍 since there's been more updates
Reran the example and everything is still working

**Review by au2 — APPROVED** [review]
Test pass and does not appear to effect the main functionality so approving. Did not check the actual algorithm.

**Pull request merged**
