### PR TITLE
MCP-2061 Evidence Summary PDF Updates

### PR DESCRIPTION
**Pull request by anthonyvelazquez**
## What was the problem?
More updates to the PDF's design

Associated tickets or Slack threads:

- [MCP-2061](https://amida.atlassian.net/browse/MCP-2061)

## How to test this PR
- Spot check some differences between the PDF in the ticket vs the generated one or verify via code

image
image
image

### CODE REVIEW

**Review by au2 — CHANGES_REQUESTED** [review]
Not everybody has access to JIRA. Please put the adequate information in the PR.

**Comment by anthonyvelazquez** [comment]
> Not everybody has access to JIRA. Please put the adequate information in the PR.

Updated with screenshots

**Review by jbregstone — CHANGES_REQUESTED** [review]
Formatting changes look good, the one thing is page size is not 8.5" x 14".

**Review by au2 — DISMISSED** [review]
1) I tried to generate the pdf with 0000. I got
{
  "claimSubmissionId": "1235",
  "status": "ERROR",
  "reason": "[Errno 13] Permission denied: '/home/docker/lib/templates/summary/generated_toc.xsl'"
}

**Review by jbregstone — CHANGES_REQUESTED** [review]
I got the same error message ^^^

**Comment by anthonyvelazquez** [comment]
@jbregstone @au2 @ianwolson 

Renamed the old hypertension PDF to run off code `0000` and made the new Evidence PDF run on code `7101`. You can either test by pasting the code into the PDF endpoint directly or call the MAS endpoint and fetch the PDF afterwards.

To simplify testing this PR since its difficult to test the visual changes, i'd say if it generates give it a 👍 if it generates and downloads successfully. @carodew and I are working together to go over the visual updates

**Review by jbregstone — APPROVED** [review]
It looks good! Great work

**Review by ianwolson — APPROVED** [review]

**Pull request merged**
